// <auto-generated />
using System;
using EFCoreCodeFirstSample_SP21_Evening.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreCodeFirstSample_SP21_Evening.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20210612234616_EFCoreCodeFirstSample-SP21-Evening.Models.RemoveEmployeeGender")]
    partial class EFCoreCodeFirstSampleSP21EveningModelsRemoveEmployeeGender
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreCodeFirstSample_SP21_Evening.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1L,
                            DateOfBirth = new DateTime(1992, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aliraza@gmail.com",
                            FirstName = "Ali",
                            LastName = "Raza",
                            PhoneNumber = "090078601"
                        },
                        new
                        {
                            EmployeeId = 2L,
                            DateOfBirth = new DateTime(1992, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asadullah@gmail.com",
                            FirstName = "Asad",
                            LastName = "Ullah",
                            PhoneNumber = "090078601"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
